### ISSUE TITLE
What does this plug-in do & work with?

### ISSUE THREAD

**Issue by codyc1515** [SmolSoftBoi/homebridge-tp-link-powerline#1]

**Comment by kheewei** [comment]
I tried installing this on my Mac instead of Synology, configured the Powerline Wifi Router/AP (https://www.tp-link.com/my/home-networking/powerline/tl-wpa8631p-kit/  --> only the bigger device which is the wifi access point can be added), and my power line wifi device was added as a... wifi router I think (there is a very slim chance that I misread and it was added as a range extender).

As to the function of the HomeKit wifi router itself, based on what I've read (https://www.imore.com/homekit-routers-everything-you-need-know) is to turn on the secure/privacy mode... and I only tried it briefly, but didn't seem to work (couldn't select the option to turn it on... either I was confused or it just doesn't work since it's not official HomeKit).

This is purely based on my trial and error, best if there was some simple documentation by the creator
